# CORRECTED FILE FOR LATEST OPERATOR
apiVersion: dynatrace.com/v1beta3  # <--- FIXED (was v1beta2)
kind: DynaKube
metadata:
  name: cluster-mydigital
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
spec:
  # Internal Private IP via Public DNS
  apiUrl: https://dynatrace.jdn.gov.my/e/ee8b6225-97b6-4cd7-bca2-bb7638ebf277/api

  oneAgent:
    # CAPITALS MATTER HERE
    classicFullStack:             # <--- FIXED (was classicFullstack)
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      env:
        - name: ONEAGENT_ENABLE_VOLUME_STORAGE
          value: "false"

  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
