apiVersion: v1
kind: Secret
metadata:
  name: cluster-mydigital
  namespace: dynatrace
type: Opaque
stringData:
  # Tokens preserved as requested
  apiToken: dt0c01.CETPZO3BRFFNG5HSQ2NLXR6L.CQMV4EABNCHBUJILI2ZPOOIGZJKHDWXIHCT7DA37ZIQEXYLUF2BF4UDDB26SWL6N
  dataIngestToken: dt0c01.CETPZO3BRFFNG5HSQ2NLXR6L.CQMV4EABNCHBUJILI2ZPOOIGZJKHDWXIHCT7DA37ZIQEXYLUF2BF4UDDB26SWL6N
---
apiVersion: dynatrace.com/v1beta3
kind: DynaKube
metadata:
  name: cluster-mydigital
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
spec:
  # Internal Private IP via Public DNS
  apiUrl: https://dynatrace.jdn.gov.my/e/ee8b6225-97b6-4cd7-bca2-bb7638ebf277/api

  skipCertCheck: true

  oneAgent:
    hostGroup: "kubernetes-mydid"
    
    # CHANGED: Switched to cloudNativeFullStack
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      # REMOVED: ONEAGENT_ENABLE_VOLUME_STORAGE. 
      # CloudNative requires the CSI volume mechanism to function correctly.

  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
    env:
      - name: DT_SERVER
        value: https://dynatrace.jdn.gov.my
