apiVersion: v1
kind: Secret
metadata:
  name: cluster-mydigital
  namespace: dynatrace
type: Opaque
data:
  # Tokens from Source 2
  apiToken: ZHQwYzAxLjVBNTZBWkE3RFpKQTRZUVdPN0NKNFRSSy5KUEFIS0FKR0xVUVI2S0RDQkJUM0hYN09DVjZNQU1TVE1GNzc2QktSNjZUM0ZYRFBBS1RQUkhZUFY3UUVSNE9V
  dataIngestToken: ZHQwYzAxLk1NRlNXUUpJNUZQMktSWVFKV0paSFdYWi5HSDVBSkQ1WjZBMzNEQTczUEI2SVhSSE40R1lMSkJRWEg1VjZNWkNWVTJKSUs3N0I0R0Y0NFZGQktUVUVZMlIy
---
apiVersion: dynatrace.com/v1beta3
kind: DynaKube
metadata:
  name: cluster-mydigital
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
    feature.dynatrace.com/injection-readonly-volume: "true"
spec:
  # API URL from Source 2
  apiUrl: https://dynatrace.jdn.gov.my/e/ee8b6225-97b6-4cd7-bca2-bb7638ebf277/api

  metadataEnrichment:
    enabled: true

  oneAgent:
    # Using Cloud Native Full Stack (Modern standard from Source 1)
    classicFullstack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists

  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
